import { ReduxProvider } from '@/store/provider'
import './globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="w-full h-full">
            <body className="flex bg-[#010C15] w-full min-h-full">
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    )
}
