import Stripes from '@/components/Stripes/Stripes'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='w-full h-full'>
      <body className='w-full h-full'>
        <main className="w-full h-full p-4 bg-[#010C15] flex relative text-white">
          <Stripes />
          <div className='w-full h-full bg-transparent border border-[#1E2D3D]/70 rounded-lg z-10'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
